/*TABLA: ESTADOS*/
INSERT INTO KIOSCO.ESTADOS VALUES (DEFAULT,'Activo','Estado para todos los elementos que tiene todas las opciones disponibles en el sistema y puede ser utilizado por todas las entidades que tengan asignado un estado.',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.ESTADOS VALUES (DEFAULT,'Bloqueado','Estado para todos los elementos que NO tienen permitido ingresar al sistema, han sido descartados para su uso por alguna falta o discrepancia en los datos. Estos elementos no pueden ser usados por ninguna entidad del sistema.',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.ESTADOS VALUES (DEFAULT,'Inactivo','Estado para todos los elementos que han sido deshabilitados del sistema, las condiciones varían dependiendo de la entidad que tenga el estado. Mientras se encuentren en este estado no pueden ser usados en el sistema, pero debe ser validado e informado a los usuarios.',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.ESTADOS VALUES (DEFAULT,'Eliminado','Estado para todos los elementos que han sido borrados lógicamente del sistema. Estos elementos no deben ser visualizado o utilizados en ninguna parte del sistema.',CURRENT_TIMESTAMP,NULL,NULL);

DELETE FROM KIOSCO.ESTADOS WHERE NOMBRE_ESTADO = 'Activo';
DELETE FROM KIOSCO.ESTADOS WHERE NOMBRE_ESTADO = 'Bloqueado';
DELETE FROM KIOSCO.ESTADOS WHERE NOMBRE_ESTADO = 'Inactivo';
DELETE FROM KIOSCO.ESTADOS WHERE NOMBRE_ESTADO = 'Eliminado';

/*TABLA: ROLES*/
INSERT INTO KIOSCO.ROLES VALUES (DEFAULT,'Administrador','Super usuario del sistema, no tiene límites para crear, actualizar, consultar y eliminar lógicamente información. Es el único con privilegios para mover de estados a los usuarios y vendedores. (Incluye funciones de los roles Cliente, Vendedor y Empleado).','',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.ROLES VALUES (DEFAULT,'Cliente','Usuario que solo debe tener cuentas por pagar o montos a su favor. Acceso solo a su información. (No incluye funciones de otros roles).','',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.ROLES VALUES (DEFAULT,'Vendedor','Usuario vendedor independiente o de una empresa. Acceso solo a su información personal y los datos de los productos que vende. (Incluye funciones del rol Cliente).','',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.ROLES VALUES (DEFAULT,'Empleado','Usuario que tiene acceso para consultar y agregar datos en las cuentas de los clientes, pero no puede eliminar y/o actualizar las cuentas. (Incluye funciones de los roles Cliente y Vendedor).','',CURRENT_TIMESTAMP,NULL,NULL);

DELETE FROM KIOSCO.ROLES WHERE NOMBRE_ROL = 'Administrador';
DELETE FROM KIOSCO.ROLES WHERE NOMBRE_ROL = 'Cliente';
DELETE FROM KIOSCO.ROLES WHERE NOMBRE_ROL = 'Vendedor';
DELETE FROM KIOSCO.ROLES WHERE NOMBRE_ROL = 'Empleado';

/*TABLA: USUARIOS*/
INSERT INTO KIOSCO.USUARIOS VALUES (DEFAULT,'17641081','V','Junior Casique','juniorcp86@gmail.com','04241996265','1','1',NULL,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.USUARIOS VALUES (DEFAULT,'5028631','V','Jesus Casique','jesuscasique55@gmail.com','04129935638','1','1',NULL,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.USUARIOS VALUES (DEFAULT,'','','','','','','',NULL,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.USUARIOS VALUES (DEFAULT,'','','','','','','',NULL,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.USUARIOS VALUES (DEFAULT,'','','','','','','',NULL,CURRENT_TIMESTAMP,NULL,NULL);

DELETE FROM KIOSCO.USUARIOS WHERE DOCUMENTO_IDENTIDAD = '17641081';
DELETE FROM KIOSCO.USUARIOS WHERE DOCUMENTO_IDENTIDAD = '5028631';

/*TABLA: TIPO_SERVICIOS*/
INSERT INTO KIOSCO.TIPO_SERVICIOS VALUES (DEFAULT,'Tarjetas telefónicas Movistar','Distribución de tarjetas telefónicas para Movistar.',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.TIPO_SERVICIOS VALUES (DEFAULT,'Tarjetas telefónicas Movilnet','Distribución de tarjetas telefónicas para Movilnet.',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.TIPO_SERVICIOS VALUES (DEFAULT,'Tarjetas telefónicas Digitel','Distribución de tarjetas telefónicas para Digitel.',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.TIPO_SERVICIOS VALUES (DEFAULT,'Tarjetas telefónicas Direct TV','Distribución de tarjetas telefónicas para Direct TV.',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.TIPO_SERVICIOS VALUES (DEFAULT,'Tarjetas telefónicas llamadas internacionales','Distribución de tarjetas telefónicas para llamadas internacionales.',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.TIPO_SERVICIOS VALUES (DEFAULT,'Revistas nacionales','Distribución de revistas nacionales.',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.TIPO_SERVICIOS VALUES (DEFAULT,'Revistas importadas','Distribución de revistas importadas.',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.TIPO_SERVICIOS VALUES (DEFAULT,'Chucherías nacionales','Distribución de chucherías nacionales.',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.TIPO_SERVICIOS VALUES (DEFAULT,'Chucherías importadas','Distribución de chucherías importadas.',CURRENT_TIMESTAMP,NULL,NULL);

DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE NOMBRE_SERVICIO = 'Tarjetas telefónicas Movistar';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE NOMBRE_SERVICIO = 'Tarjetas telefónicas Movilnet';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE NOMBRE_SERVICIO = 'Tarjetas telefónicas Digitel';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE NOMBRE_SERVICIO = 'Tarjetas telefónicas Direct TV';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE NOMBRE_SERVICIO = 'Tarjetas telefónicas llamadas internacionales';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE NOMBRE_SERVICIO = 'Revistas nacionales';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE NOMBRE_SERVICIO = 'Revistas importadas';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE NOMBRE_SERVICIO = 'Chucherías nacionales';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE NOMBRE_SERVICIO = 'Chucherías importadas';

/*TABLA: PROVEEDORES*/
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-294556507','Distribuida Careste, C.A.','1',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-000067481','C.A. Cigarrera Bigott','1',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-313691976','Comunicaciones Movilcard 21, C.A.','1',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-304689713','Corporación Digitel','1',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-305807574','Distribuidora Sobralia C.A.','1',CURRENT_TIMESTAMP,NULL,NULL);

DELETE FROM KIOSCO.PROVEEDORES WHERE RIF = 'J-294556507';
DELETE FROM KIOSCO.PROVEEDORES WHERE RIF = 'J-000067481';
DELETE FROM KIOSCO.PROVEEDORES WHERE RIF = 'J-313691976';
DELETE FROM KIOSCO.PROVEEDORES WHERE RIF = 'J-304689713';
DELETE FROM KIOSCO.PROVEEDORES WHERE RIF = 'J-305807574';

/*TABLA: CONTACTO_PROVEEDOR*/
INSERT INTO KIOSCO.CONTACTO_PROVEEDOR VALUES ('','','','',NULL,NULL,'',NULL,NULL);
INSERT INTO KIOSCO.CONTACTO_PROVEEDOR VALUES ('','','','',NULL,NULL,'',NULL,NULL);
INSERT INTO KIOSCO.CONTACTO_PROVEEDOR VALUES ('','','','',NULL,NULL,'',NULL,NULL);
INSERT INTO KIOSCO.CONTACTO_PROVEEDOR VALUES ('','','','',NULL,NULL,'',NULL,NULL);
INSERT INTO KIOSCO.CONTACTO_PROVEEDOR VALUES ('','','','',NULL,NULL,'',NULL,NULL);

DELETE FROM KIOSCO.CONTACTO_PROVEEDOR WHERE ID_PROVEEDOR = '' AND ID_USUARIO = '';
DELETE FROM KIOSCO.CONTACTO_PROVEEDOR WHERE ID_PROVEEDOR = '' AND ID_USUARIO = '';
DELETE FROM KIOSCO.CONTACTO_PROVEEDOR WHERE ID_PROVEEDOR = '' AND ID_USUARIO = '';
DELETE FROM KIOSCO.CONTACTO_PROVEEDOR WHERE ID_PROVEEDOR = '' AND ID_USUARIO = '';
DELETE FROM KIOSCO.CONTACTO_PROVEEDOR WHERE ID_PROVEEDOR = '' AND ID_USUARIO = '';

/*TABLA: PROVEEDORES_TIPO_SERVICIOS*/
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('','');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('','');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('','');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('','');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('','');

DELETE FROM KIOSCO.PROVEEDORES_TIPO_SERVICIOS WHERE PROVEEDORES_ID_PROVEEDOR = '' AND TIPO_SERVICIOS_ID_TIPO_SERVICIO = '';
DELETE FROM KIOSCO.PROVEEDORES_TIPO_SERVICIOS WHERE PROVEEDORES_ID_PROVEEDOR = '' AND TIPO_SERVICIOS_ID_TIPO_SERVICIO = '';
DELETE FROM KIOSCO.PROVEEDORES_TIPO_SERVICIOS WHERE PROVEEDORES_ID_PROVEEDOR = '' AND TIPO_SERVICIOS_ID_TIPO_SERVICIO = '';
DELETE FROM KIOSCO.PROVEEDORES_TIPO_SERVICIOS WHERE PROVEEDORES_ID_PROVEEDOR = '' AND TIPO_SERVICIOS_ID_TIPO_SERVICIO = '';
DELETE FROM KIOSCO.PROVEEDORES_TIPO_SERVICIOS WHERE PROVEEDORES_ID_PROVEEDOR = '' AND TIPO_SERVICIOS_ID_TIPO_SERVICIO = '';

SHOW DATABASES;