/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: CONTACTO_PROVEEDOR
* FECHA DE CREACIÓN: 03/11/2015
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la eliminación de la tabla mencionada. Es el rollback del script 07_CREATE_TABLE_CONTACTO_PROVEEDOR.sql
*/

USE KIOSCO;

DROP TABLE IF EXISTS KIOSCO.CONTACTO_PROVEEDOR;
