/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: USUARIOS
* FECHA DE CREACIÓN: DD/MM/AAAA
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la eliminación de la tabla mencionada. Es el rollback del script 04_CREATE_TABLE_USUARIOS.sql
*/

DROP TABLE IF EXISTS KIOSCO.USUARIOS;