/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: ESTADOS
* FECHA DE CREACIÓN: DD/MM/AAAA
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la eliminación de los datos en la tabla mencionada. Es el rollback del script 09_INSERT_DATA_ESTADOS.sql
*/

DELETE FROM KIOSCO.ESTADOS WHERE NOMBRE_ESTADO = 'Activo';
DELETE FROM KIOSCO.ESTADOS WHERE NOMBRE_ESTADO = 'Bloqueado';
DELETE FROM KIOSCO.ESTADOS WHERE NOMBRE_ESTADO = 'Inactivo';
DELETE FROM KIOSCO.ESTADOS WHERE NOMBRE_ESTADO = 'Eliminado';