/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: TIPO_SERVICIOS
* FECHA DE CREACIÓN: DD/MM/AAAA
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la eliminación de la tabla mencionada. Es el rollback del script 05_CREATE_TABLE_TIPO_SERVICIOS.sql
*/

DROP TABLE IF EXISTS KIOSCO.TIPO_SERVICIOS;