/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: ROLES
* FECHA DE CREACIÓN: DD/MM/AAAA
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la eliminación de los datos en la tabla mencionada. Es el rollback del script 10_INSERT_DATA_ROLES.sql
*/

DELETE FROM KIOSCO.ROLES WHERE NOMBRE_ROL = 'Administrador';
DELETE FROM KIOSCO.ROLES WHERE NOMBRE_ROL = 'Cliente';
DELETE FROM KIOSCO.ROLES WHERE NOMBRE_ROL = 'Vendedor';
DELETE FROM KIOSCO.ROLES WHERE NOMBRE_ROL = 'Empleado';