/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: PROVEEDORES
* FECHA DE CREACIÓN: DD/MM/AAAA
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la eliminación de los datos en la tabla mencionada. Es el rollback del script 13_INSERT_DATA_PROVEEDORES.sql
*/

DELETE FROM KIOSCO.PROVEEDORES WHERE RIF = 'J-294556507';
DELETE FROM KIOSCO.PROVEEDORES WHERE RIF = 'J-000067481';
DELETE FROM KIOSCO.PROVEEDORES WHERE RIF = 'J-313691976';
DELETE FROM KIOSCO.PROVEEDORES WHERE RIF = 'J-304689713';
DELETE FROM KIOSCO.PROVEEDORES WHERE RIF = 'J-305807574';