/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: TIPO_SERVICIOS
* FECHA DE CREACIÓN: 03/11/2015
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la eliminación de los datos en la tabla mencionada. Es el rollback del script 12_INSERT_DATA_TIPO_SERVICIOS.sql
*/

USE KIOSCO;

DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE ID_TIPO_SERVICIO = '1';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE ID_TIPO_SERVICIO = '2';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE ID_TIPO_SERVICIO = '3';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE ID_TIPO_SERVICIO = '4';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE ID_TIPO_SERVICIO = '5';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE ID_TIPO_SERVICIO = '6';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE ID_TIPO_SERVICIO = '7';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE ID_TIPO_SERVICIO = '8';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE ID_TIPO_SERVICIO = '9';
