/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: ROLES
* FECHA DE CREACIÓN: 03/11/2015
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la eliminación de los datos en la tabla mencionada. Es el rollback del script 10_INSERT_DATA_ROLES.sql
*/

USE `KIOSCO`;

DELETE FROM KIOSCO.ROLES WHERE ID_ROL = '1';
DELETE FROM KIOSCO.ROLES WHERE ID_ROL = '2';
DELETE FROM KIOSCO.ROLES WHERE ID_ROL = '3';
DELETE FROM KIOSCO.ROLES WHERE ID_ROL = '4';
