/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: CONTACTO_PROVEEDOR
* FECHA DE CREACIÓN: DD/MM/AAAA
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la eliminación de los datos en la tabla mencionada. Es el rollback del script 14_INSERT_DATA_CONTACTO_PROVEEDOR.sql
*/

DELETE FROM KIOSCO.CONTACTO_PROVEEDOR WHERE ID_PROVEEDOR = '' AND ID_USUARIO = '';
DELETE FROM KIOSCO.CONTACTO_PROVEEDOR WHERE ID_PROVEEDOR = '' AND ID_USUARIO = '';
DELETE FROM KIOSCO.CONTACTO_PROVEEDOR WHERE ID_PROVEEDOR = '' AND ID_USUARIO = '';
DELETE FROM KIOSCO.CONTACTO_PROVEEDOR WHERE ID_PROVEEDOR = '' AND ID_USUARIO = '';
DELETE FROM KIOSCO.CONTACTO_PROVEEDOR WHERE ID_PROVEEDOR = '' AND ID_USUARIO = '';