/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: PROVEEDORES_TIPO_SERVICIOS
* FECHA DE CREACIÓN: DD/MM/AAAA
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la eliminación de los datos en la tabla mencionada. Es el rollback del script 15_INSERT_DATA_PROVEEDORES_TIPO_SERVICIOS.sql
*/

DELETE FROM KIOSCO.PROVEEDORES_TIPO_SERVICIOS WHERE PROVEEDORES_ID_PROVEEDOR = '' AND TIPO_SERVICIOS_ID_TIPO_SERVICIO = '';
DELETE FROM KIOSCO.PROVEEDORES_TIPO_SERVICIOS WHERE PROVEEDORES_ID_PROVEEDOR = '' AND TIPO_SERVICIOS_ID_TIPO_SERVICIO = '';
DELETE FROM KIOSCO.PROVEEDORES_TIPO_SERVICIOS WHERE PROVEEDORES_ID_PROVEEDOR = '' AND TIPO_SERVICIOS_ID_TIPO_SERVICIO = '';
DELETE FROM KIOSCO.PROVEEDORES_TIPO_SERVICIOS WHERE PROVEEDORES_ID_PROVEEDOR = '' AND TIPO_SERVICIOS_ID_TIPO_SERVICIO = '';
DELETE FROM KIOSCO.PROVEEDORES_TIPO_SERVICIOS WHERE PROVEEDORES_ID_PROVEEDOR = '' AND TIPO_SERVICIOS_ID_TIPO_SERVICIO = '';