/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: USUARIOS
* FECHA DE CREACIÓN: DD/MM/AAAA
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la eliminación de los datos en la tabla mencionada. Es el rollback del script 11_INSERT_DATA_USUARIOS.sql
*/

DELETE FROM KIOSCO.USUARIOS WHERE DOCUMENTO_IDENTIDAD = '17641081';
DELETE FROM KIOSCO.USUARIOS WHERE DOCUMENTO_IDENTIDAD = '5028631';