/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: CONTACTO_PROVEEDOR
* FECHA DE CREACIÓN: 03/11/2015
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la eliminación de los datos en la tabla mencionada. Es el rollback del script 14_INSERT_DATA_CONTACTO_PROVEEDOR.sql
*/

USE `KIOSCO`;

DELETE FROM KIOSCO.CONTACTO_PROVEEDOR WHERE ID_CONTACTO = '1';
