/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: TIPO_SERVICIOS
* FECHA DE CREACIÓN: DD/MM/AAAA
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la eliminación de los datos en la tabla mencionada. Es el rollback del script 12_INSERT_DATA_TIPO_SERVICIOS.sql
*/

DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE NOMBRE_SERVICIO = 'Tarjetas telefónicas Movistar';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE NOMBRE_SERVICIO = 'Tarjetas telefónicas Movilnet';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE NOMBRE_SERVICIO = 'Tarjetas telefónicas Digitel';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE NOMBRE_SERVICIO = 'Tarjetas telefónicas Direct TV';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE NOMBRE_SERVICIO = 'Tarjetas telefónicas llamadas internacionales';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE NOMBRE_SERVICIO = 'Revistas nacionales';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE NOMBRE_SERVICIO = 'Revistas importadas';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE NOMBRE_SERVICIO = 'Chucherías nacionales';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE NOMBRE_SERVICIO = 'Chucherías importadas';