/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: ESTADOS
* FECHA DE CREACIÓN: 03/11/2015
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la eliminación de los datos en la tabla mencionada. Es el rollback del script 09_INSERT_DATA_ESTADOS.sql
*/

USE KIOSCO;

DELETE FROM KIOSCO.ESTADOS WHERE ID_ESTADO = '1';
DELETE FROM KIOSCO.ESTADOS WHERE ID_ESTADO = '2';
DELETE FROM KIOSCO.ESTADOS WHERE ID_ESTADO = '3';
DELETE FROM KIOSCO.ESTADOS WHERE ID_ESTADO = '4';
