/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: PROVEEDORES_TIPOS_SERVICIOS
* FECHA DE CREACIÓN: 03/11/2015
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 09/12/2015
* ACTUALIZADO POR: Junior Casique
* DESCRIPCIÓN: Script para realizar la eliminación de los datos en la tabla mencionada. Es el rollback del script 08_INSERT_DATA_PROVEEDORES_TIPO_SERVICIOS.sql. Se actulizó por cambio en el nombre de la tabla.
*/

USE KIOSCO;

DELETE FROM KIOSCO.PROVEEDORES_TIPOS_SERVICIOS WHERE PROVEEDORES_ID_PROVEEDOR = '1' AND TIPO_SERVICIOS_ID_TIPO_SERVICIO = '1';
DELETE FROM KIOSCO.PROVEEDORES_TIPOS_SERVICIOS WHERE PROVEEDORES_ID_PROVEEDOR = '3' AND TIPO_SERVICIOS_ID_TIPO_SERVICIO = '1';
