/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: PRODUCTOS
* FECHA DE CREACIÓN: 13/11/2015
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la eliminación de los datos en la tabla mencionada. Es el rollback del script 09_INSERT_DATA_PRODUCTOS.sql
*/

USE KIOSCO;

DELETE FROM KIOSCO.PRODUCTOS WHERE ID_PRODUCTO = '1';
DELETE FROM KIOSCO.PRODUCTOS WHERE ID_PRODUCTO = '2';
DELETE FROM KIOSCO.PRODUCTOS WHERE ID_PRODUCTO = '3';
DELETE FROM KIOSCO.PRODUCTOS WHERE ID_PRODUCTO = '4';
DELETE FROM KIOSCO.PRODUCTOS WHERE ID_PRODUCTO = '5';
DELETE FROM KIOSCO.PRODUCTOS WHERE ID_PRODUCTO = '6';
