/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: PROVEEDORES_PRODUCTOS
* FECHA DE CREACIÓN: 13/11/2015
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la eliminación de los datos en la tabla mencionada. Es el rollback del script 17_INSERT_DATA_PROVEEDORES_PRODUCTOS.sql
*/

USE KIOSCO;

DELETE FROM KIOSCO.PROVEEDORES_PRODUCTOS WHERE PROVEEDORES_ID_PROVEEDOR = '1' AND PRODUCTOS_ID_PRODUCTO = '';
