/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: CUENTA_DETALLES
* FECHA DE CREACIÓN: 13/11/2015
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la eliminación de los datos en la tabla mencionada. Es el rollback del script 14_INSERT_DATA_CUENTA_DETALLES.sql
*/

USE KIOSCO;

DELETE FROM KIOSCO.CUENTA_DETALLES WHERE ID_CUENTA_DETALLE = '1';
