/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: PROVEEDORES
* FECHA DE CREACIÓN: 03/11/2015
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 09/12(2015
* ACTUALIZADO POR: Junior Casique
* DESCRIPCIÓN: Script para realizar la inserción de datos en la tabla mencionada. Se ajusto script debido por cambio en la estructura de la tabla relacional.
*/

USE KIOSCO;

INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-294556507','Distribuidora Careste, C.A.','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-000067481','C.A. Cigarrera Bigott','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-313691976','Comunicaciones Movilcard 21, C.A.','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-304689713','Corporación Digitel','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-305807574','Distribuidora Sobralia C.A.','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-294556604','Distribuidora Caroeste, C.A.','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-295535481','Distribuidora Unicandy','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-000115575','Distribuidora Santiago C.A.','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-404184619','Distribuidora Capi 1725 C.A.','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'V-14965373','Jaime Rodriguez','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'V-4746745','Ana Nava','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'V-21283829','Jhonny Murillo','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'V-11680694','Omar Moros','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-000129266','Nestlé Savoy','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'V-10473408','Humberto Pestana','1',CURRENT_DATE(),NULL,NULL);