/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: PROVEEDORES
* FECHA DE CREACIÓN: 03/11/2015
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la inserción de datos en la tabla mencionada.
*/

USE KIOSCO;

INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-294556507','Distribuidora Careste, C.A.','1','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-000067481','C.A. Cigarrera Bigott','16','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-313691976','Comunicaciones Movilcard 21, C.A.','1','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-304689713','Corporación Digitel','3','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-305807574','Distribuidora Sobralia C.A.','7','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-294556604','Distribuidora Caroeste, C.A.','1','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-295535481','Distribuidora Unicandy','8','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-000115575','Distribuidora Santiago C.A.','6','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-404184619','Distribuidora Capi 1725 C.A.','4','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'V-14965373','Jaime Rodriguez','13','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'V-4746745','Ana Nava','17','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'V-21283829','Jhonny Murillo','10','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'V-11680694','Omar Moros','1','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-000129266','Nestlé Savoy','8','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'V-10473408','Humberto Pestana','1','1',CURRENT_DATE(),NULL,NULL);
