/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: PROVEEDORES_TIPO_SERVICIOS
* FECHA DE CREACIÓN: 03/11/2015
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la inserción de datos en la tabla mencionada.
*/

USE KIOSCO;

INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('1','1');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('2','16');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('3','1');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('4','3');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('5','6');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('5','7');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('6','1');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('7','8');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('7','9');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('8','6');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('8','7');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('9','');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('10','13');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('11','17');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('12','10');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('13','1');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('13','8');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('13','9');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('14','8');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('14','9');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('15','2');
