/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: IVA
* FECHA DE CREACIÓN: 16/11/2015
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la inserción de datos en la tabla mencionada.
*/

USE KIOSCO;

INSERT INTO KIOSCO.IVA VALUES (DEFAULT,'12.00','1',CURRENT_DATE,NULL,NULL);
