/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: CUENTAS
* FECHA DE CREACIÓN: 13/11/2015
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la inserción de datos en la tabla mencionada.
*/

USE KIOSCO;

INSERT INTO KIOSCO.CUENTAS VALUES (DEFAULT,'8','1510.00','1',CURRENT_DATE,NULL,NULL);
INSERT INTO KIOSCO.CUENTAS VALUES (DEFAULT,'12','200.00','1',CURRENT_DATE,NULL,NULL);
INSERT INTO KIOSCO.CUENTAS VALUES (DEFAULT,'14','6490.00','1',CURRENT_DATE,NULL,NULL);
INSERT INTO KIOSCO.CUENTAS VALUES (DEFAULT,'7','2116.00','1',CURRENT_DATE,NULL,NULL);
INSERT INTO KIOSCO.CUENTAS VALUES (DEFAULT,'10','3925.00','1',CURRENT_DATE,NULL,NULL);
INSERT INTO KIOSCO.CUENTAS VALUES (DEFAULT,'9','520.00','1',CURRENT_DATE,NULL,NULL);
INSERT INTO KIOSCO.CUENTAS VALUES (DEFAULT,'13','190.00','1',CURRENT_DATE,NULL,NULL);
