/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: CUENTA_DETALLES
* FECHA DE CREACIÓN: 16/11/2015
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la inserción de datos en la tabla mencionada.
*/

USE KIOSCO;

INSERT INTO KIOSCO.CUENTA_DETALLES VALUES (DEFAULT,'1','1','1','1','Se esta agregando un monto general','250.00',CURRENT_DATE,NULL,NULL);
