/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: COSTO_PRODUCTOS
* FECHA DE CREACIÓN: 16/11/2015
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la inserción de datos en la tabla mencionada.
*/

USE KIOSCO;

INSERT INTO KIOSCO.COSTO_PRODUCTOS VALUES (DEFAULT,'1','1','10.00','11.2','1',CURRENT_DATE,NULL);
