/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: USUARIOS
* FECHA DE CREACIÓN: DD/MM/AAAA
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la inserción de datos en la tabla mencionada.
*/

INSERT INTO KIOSCO.USUARIOS VALUES (DEFAULT,'17641081','V','Junior Casique','juniorcp86@gmail.com','04241996265','1','1',NULL,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.USUARIOS VALUES (DEFAULT,'5028631','V','Jesus Casique','jesuscasique55@gmail.com','04129935638','1','1',NULL,CURRENT_TIMESTAMP,NULL,NULL);