/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: PROVEEDORES
* FECHA DE CREACIÓN: DD/MM/AAAA
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la inserción de datos en la tabla mencionada.
*/

INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-294556507','Distribuida Careste, C.A.','1',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-000067481','C.A. Cigarrera Bigott','1',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-313691976','Comunicaciones Movilcard 21, C.A.','1',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-304689713','Corporación Digitel','1',CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-305807574','Distribuidora Sobralia C.A.','1',CURRENT_TIMESTAMP,NULL,NULL);