/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: PROVEEDORES
* FECHA DE CREACIÓN: DD/MM/AAAA
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la inserción de datos en la tabla mencionada.
*/

INSERT INTO KIOSCO.CONTACTO_PROVEEDOR VALUES ('','','','',NULL,NULL,'',NULL,NULL);
INSERT INTO KIOSCO.CONTACTO_PROVEEDOR VALUES ('','','','',NULL,NULL,'',NULL,NULL);
INSERT INTO KIOSCO.CONTACTO_PROVEEDOR VALUES ('','','','',NULL,NULL,'',NULL,NULL);
INSERT INTO KIOSCO.CONTACTO_PROVEEDOR VALUES ('','','','',NULL,NULL,'',NULL,NULL);
INSERT INTO KIOSCO.CONTACTO_PROVEEDOR VALUES ('','','','',NULL,NULL,'',NULL,NULL);