/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: PROVEEDORES
* FECHA DE CREACIÓN: 03/11/2015
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la inserción de datos en la tabla mencionada.
*/

USE 'KIOSCO';

INSERT INTO KIOSCO.CONTACTO_PROVEEDOR VALUES (DEFAULT,'1','Doni','04241234567',NULL,NULL,'donilatin@hotmail.com',NULL,NULL);
