/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: PROVEEDORES_TIPO_SERVICIOS
* FECHA DE CREACIÓN: 03/11/2015
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la inserción de datos en la tabla mencionada.
*/

USE KIOSCO;

INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('1','1');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('3','1');
