/*
* NOMBRE BASE DE DATOS: KIOSCO
* NOMBRE DE LA TABLA: PROVEEDORES_TIPO_SERVICIOS
* FECHA DE CREACIÓN: DD/MM/AAAA
* CREADO POR: Junior Casique
* FECHA DE ACTUALIZACIÓN: 
* ACTUALIZADO POR: 
* DESCRIPCIÓN: Script para realizar la inserción de datos en la tabla mencionada.
*/

INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('','');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('','');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('','');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('','');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('','');