/*CONSULTA PARA TODOS LOS USUARIOS*/
SELECT CONCAT(IF(AA.TIPO_DOCUMENTO_IDENTIDAD = '1','V-','E-'),IF(LENGTH(AA.DOCUMENTO_IDENTIDAD) = '9',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -9 FOR 3),IF(LENGTH(AA.DOCUMENTO_IDENTIDAD) = '8',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -8 FOR 2),SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -7 FOR 1))),'.',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -6 FOR 3),'.',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -3)) "Cédula de Identidad"
,AA.NOMBRE_APELLIDO_USUARIO "Nombre y Apellido"
,AA.CORREO_ELECTRONICO "Email"
,CONCAT(SUBSTRING(AA.NUMERO_CONTACTO,1,4),'-',SUBSTRING(AA.NUMERO_CONTACTO,5,11)) "Número Telefónico"
,IF(AA.SEXO = '1','Masculino','Femenino') "Sexo"
,BB.NOMBRE_ESTADO "Estado"
,CC.NOMBRE_ROL "Rol"
,DATE_FORMAT(AA.FECHA_CREACION,'%d-%m-%y') "Fecha de Creación"
,IF(AA.ULTIMA_SESION IS NULL,'No ha iniciado sesión',DATE_FORMAT(AA.ULTIMA_SESION,'%d-%m-%Y')) "Último Inicio de Sesión"
FROM KIOSCO.USUARIOS AA JOIN KIOSCO.ESTADOS BB ON AA.ID_ESTADO = BB.ID_ESTADO
JOIN KIOSCO.ROLES CC ON AA.ID_ROL = CC.ID_ROL
ORDER BY AA.NOMBRE_APELLIDO_USUARIO ASC;

/*CONSULTA PARA TODOS LOS USUARIOS ACTIVOS*/
SELECT CONCAT(IF(AA.TIPO_DOCUMENTO_IDENTIDAD = '1','V-','E-'),IF(LENGTH(AA.DOCUMENTO_IDENTIDAD) = '9',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -9 FOR 3),IF(LENGTH(AA.DOCUMENTO_IDENTIDAD) = '8',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -8 FOR 2),SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -7 FOR 1))),'.',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -6 FOR 3),'.',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -3)) "Cédula de Identidad"
,AA.NOMBRE_APELLIDO_USUARIO "Nombre y Apellido"
,AA.CORREO_ELECTRONICO "Email"
,CONCAT(SUBSTRING(AA.NUMERO_CONTACTO,1,4),'-',SUBSTRING(AA.NUMERO_CONTACTO,5,11)) "Número Telefónico"
,IF(AA.SEXO = '1','Masculino','Femenino') "Sexo"
,BB.NOMBRE_ESTADO "Estado"
,CC.NOMBRE_ROL "Rol"
,DATE_FORMAT(AA.FECHA_CREACION,'%d-%m-%y') "Fecha de Creación"
,IF(AA.ULTIMA_SESION IS NULL,'No ha iniciado sesión',DATE_FORMAT(AA.ULTIMA_SESION,'%d-%m-%Y')) "Último Inicio de Sesión"
FROM KIOSCO.USUARIOS AA JOIN KIOSCO.ESTADOS BB ON AA.ID_ESTADO = BB.ID_ESTADO
JOIN KIOSCO.ROLES CC ON AA.ID_ROL = CC.ID_ROL
WHERE AA.FECHA_ELIMINACION IS NULL
ORDER BY AA.NOMBRE_APELLIDO_USUARIO ASC;

/*CONSULTA PARA TODOS LOS USUARIOS INACTIVOS*/
SELECT CONCAT(IF(AA.TIPO_DOCUMENTO_IDENTIDAD = '1','V-','E-'),IF(LENGTH(AA.DOCUMENTO_IDENTIDAD) = '9',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -9 FOR 3),IF(LENGTH(AA.DOCUMENTO_IDENTIDAD) = '8',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -8 FOR 2),SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -7 FOR 1))),'.',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -6 FOR 3),'.',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -3)) "Cédula de Identidad"
,AA.NOMBRE_APELLIDO_USUARIO "Nombre y Apellido"
,AA.CORREO_ELECTRONICO "Email"
,CONCAT(SUBSTRING(AA.NUMERO_CONTACTO,1,4),'-',SUBSTRING(AA.NUMERO_CONTACTO,5,11)) "Número Telefónico"
,IF(AA.SEXO = '1','Masculino','Femenino') "Sexo"
,BB.NOMBRE_ESTADO "Estado"
,CC.NOMBRE_ROL "Rol"
,DATE_FORMAT(AA.FECHA_CREACION,'%d-%m-%y') "Fecha de Creación"
,IF(AA.ULTIMA_SESION IS NULL,'No ha iniciado sesión',DATE_FORMAT(AA.ULTIMA_SESION,'%d-%m-%Y')) "Último Inicio de Sesión"
FROM KIOSCO.USUARIOS AA JOIN KIOSCO.ESTADOS BB ON AA.ID_ESTADO = BB.ID_ESTADO
JOIN KIOSCO.ROLES CC ON AA.ID_ROL = CC.ID_ROL
WHERE AA.FECHA_ELIMINACION IS NOT NULL
ORDER BY AA.NOMBRE_APELLIDO_USUARIO ASC;

/*CONSULTA PARA UN USUARIO ESPECÍFICO*/
SELECT CONCAT(IF(AA.TIPO_DOCUMENTO_IDENTIDAD = '1','V-','E-'),IF(LENGTH(AA.DOCUMENTO_IDENTIDAD) = '9',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -9 FOR 3),IF(LENGTH(AA.DOCUMENTO_IDENTIDAD) = '8',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -8 FOR 2),SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -7 FOR 1))),'.',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -6 FOR 3),'.',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -3)) "Cédula de Identidad"
,AA.NOMBRE_APELLIDO_USUARIO "Nombre y Apellido"
,AA.CORREO_ELECTRONICO "Email"
,CONCAT(SUBSTRING(AA.NUMERO_CONTACTO,1,4),'-',SUBSTRING(AA.NUMERO_CONTACTO,5,11)) "Número Telefónico"
,IF(AA.SEXO = '1','Masculino','Femenino') "Sexo"
,BB.NOMBRE_ESTADO "Estado"
,CC.NOMBRE_ROL "Rol"
,DATE_FORMAT(AA.FECHA_CREACION,'%d-%m-%y') "Fecha de Creación"
,IF(AA.ULTIMA_SESION IS NULL,'No ha iniciado sesión',DATE_FORMAT(AA.ULTIMA_SESION,'%d-%m-%Y')) "Último Inicio de Sesión"
FROM KIOSCO.USUARIOS AA JOIN KIOSCO.ESTADOS BB ON AA.ID_ESTADO = BB.ID_ESTADO
JOIN KIOSCO.ROLES CC ON AA.ID_ROL = CC.ID_ROL
WHERE AA.DOCUMENTO_IDENTIDAD = ''
OR AA.CORREO_ELECTRONICO LIKE '%%'
OR AA.NOMBRE_APELLIDO_USUARIO LIKE '%%'
OR AA.NUMERO_CONTACTO = ''
ORDER BY AA.NOMBRE_APELLIDO_USUARIO ASC;












/*CONSULTA PARA TODAS LAS CUENTAS*/
SELECT BB.NOMBRE_APELLIDO_USUARIO "Cliente con Deuda"
,CONCAT(IF(BB.TIPO_DOCUMENTO_IDENTIDAD = '1','V-','E-'),IF(LENGTH(BB.DOCUMENTO_IDENTIDAD) = '9',SUBSTRING(BB.DOCUMENTO_IDENTIDAD FROM -9 FOR 3),IF(LENGTH(BB.DOCUMENTO_IDENTIDAD) = '8',SUBSTRING(BB.DOCUMENTO_IDENTIDAD FROM -8 FOR 2),SUBSTRING(BB.DOCUMENTO_IDENTIDAD FROM -7 FOR 1))),'.',SUBSTRING(BB.DOCUMENTO_IDENTIDAD FROM -6 FOR 3),'.',SUBSTRING(BB.DOCUMENTO_IDENTIDAD FROM -3)) "Cédula de Identidad"
,CONCAT('Bs. ',FORMAT(AA.TOTAL_CUENTA,2)) "Total Deuda"
,DATE_FORMAT(AA.FECHA_CREACION,'%d-%m-%y') "Fecha de Creación"
FROM KIOSCO.CUENTAS AA JOIN KIOSCO.USUARIOS BB ON AA.ID_USUARIO = BB.ID_USUARIO
ORDER BY BB.NOMBRE_APELLIDO_USUARIO ASC;

/*CONSULTA PARA TODAS LAS CUENTAS ACTIVAS*/
SELECT BB.NOMBRE_APELLIDO_USUARIO "Cliente con Deuda"
,CONCAT(IF(BB.TIPO_DOCUMENTO_IDENTIDAD = '1','V-','E-'),IF(LENGTH(BB.DOCUMENTO_IDENTIDAD) = '9',SUBSTRING(BB.DOCUMENTO_IDENTIDAD FROM -9 FOR 3),IF(LENGTH(BB.DOCUMENTO_IDENTIDAD) = '8',SUBSTRING(BB.DOCUMENTO_IDENTIDAD FROM -8 FOR 2),SUBSTRING(BB.DOCUMENTO_IDENTIDAD FROM -7 FOR 1))),'.',SUBSTRING(BB.DOCUMENTO_IDENTIDAD FROM -6 FOR 3),'.',SUBSTRING(BB.DOCUMENTO_IDENTIDAD FROM -3)) "Cédula de Identidad"
,CONCAT('Bs. ',FORMAT(AA.TOTAL_CUENTA,2)) "Total Deuda"
,DATE_FORMAT(AA.FECHA_CREACION,'%d-%m-%y') "Fecha de Creación"
FROM KIOSCO.CUENTAS AA JOIN KIOSCO.USUARIOS BB ON AA.ID_USUARIO = BB.ID_USUARIO
WHERE AA.ID_ESTADO = '1'
ORDER BY BB.NOMBRE_APELLIDO_USUARIO ASC;

/*CONSULTA PARA TODAS LAS CUENTAS INACTIVAS*/
SELECT BB.NOMBRE_APELLIDO_USUARIO "Cliente con Deuda"
,CONCAT(IF(BB.TIPO_DOCUMENTO_IDENTIDAD = '1','V-','E-'),IF(LENGTH(BB.DOCUMENTO_IDENTIDAD) = '9',SUBSTRING(BB.DOCUMENTO_IDENTIDAD FROM -9 FOR 3),IF(LENGTH(BB.DOCUMENTO_IDENTIDAD) = '8',SUBSTRING(BB.DOCUMENTO_IDENTIDAD FROM -8 FOR 2),SUBSTRING(BB.DOCUMENTO_IDENTIDAD FROM -7 FOR 1))),'.',SUBSTRING(BB.DOCUMENTO_IDENTIDAD FROM -6 FOR 3),'.',SUBSTRING(BB.DOCUMENTO_IDENTIDAD FROM -3)) "Cédula de Identidad"
,CONCAT('Bs. ',FORMAT(AA.TOTAL_CUENTA,2)) "Total Deuda"
,DATE_FORMAT(AA.FECHA_CREACION,'%d-%m-%y') "Fecha de Creación"
FROM KIOSCO.CUENTAS AA JOIN KIOSCO.USUARIOS BB ON AA.ID_USUARIO = BB.ID_USUARIO
WHERE AA.ID_ESTADO = '0'
ORDER BY BB.NOMBRE_APELLIDO_USUARIO ASC;

/*CONSULTA PARA TODAS LAS CUENTAS DE UN USUARIO ESPECÍFICO*/
SELECT BB.NOMBRE_APELLIDO_USUARIO "Cliente con Deuda"
,CONCAT(IF(BB.TIPO_DOCUMENTO_IDENTIDAD = '1','V-','E-'),IF(LENGTH(BB.DOCUMENTO_IDENTIDAD) = '9',SUBSTRING(BB.DOCUMENTO_IDENTIDAD FROM -9 FOR 3),IF(LENGTH(BB.DOCUMENTO_IDENTIDAD) = '8',SUBSTRING(BB.DOCUMENTO_IDENTIDAD FROM -8 FOR 2),SUBSTRING(BB.DOCUMENTO_IDENTIDAD FROM -7 FOR 1))),'.',SUBSTRING(BB.DOCUMENTO_IDENTIDAD FROM -6 FOR 3),'.',SUBSTRING(BB.DOCUMENTO_IDENTIDAD FROM -3)) "Cédula de Identidad"
,CONCAT('Bs. ',FORMAT(AA.TOTAL_CUENTA,2)) "Total Deuda"
,DATE_FORMAT(AA.FECHA_CREACION,'%d-%m-%y') "Fecha de Creación"
FROM KIOSCO.CUENTAS AA JOIN KIOSCO.USUARIOS BB ON AA.ID_USUARIO = BB.ID_USUARIO
WHERE BB.NOMBRE_APELLIDO_USUARIO LIKE '%%'
OR BB.DOCUMENTO_IDENTIDAD = ''
ORDER BY BB.NOMBRE_APELLIDO_USUARIO ASC;

/*CONSULTA PARA TODOS LOS DETALLES DE LAS CUENTAS*/
SELECT CC.NOMBRE_APELLIDO_USUARIO "Cliente con Deuda"
,CONCAT(IF(CC.TIPO_DOCUMENTO_IDENTIDAD = '1','V-','E-'),IF(LENGTH(CC.DOCUMENTO_IDENTIDAD) = '9',SUBSTRING(CC.DOCUMENTO_IDENTIDAD FROM -9 FOR 3),IF(LENGTH(CC.DOCUMENTO_IDENTIDAD) = '8',SUBSTRING(CC.DOCUMENTO_IDENTIDAD FROM -8 FOR 2),SUBSTRING(CC.DOCUMENTO_IDENTIDAD FROM -7 FOR 1))),'.',SUBSTRING(CC.DOCUMENTO_IDENTIDAD FROM -6 FOR 3),'.',SUBSTRING(CC.DOCUMENTO_IDENTIDAD FROM -3)) "Cédula de Identidad"
,DD.NOMBRE_PRODUCTO "Artículo"
,IF(AA.TIPO_DETALLE = '1','Aumento de la deuda','Abono a la deuda') "Tipo de Detalle"
,AA.DESCRIPCION "Descripción del ítem"
,CONCAT('Bs. ',FORMAT(AA.MONTO_DETALLE,2)) "Monto del Producto"
,DATE_FORMAT(AA.FECHA_CREACION,'%d-%m-%y') "Fecha de Creación"
FROM KIOSCO.CUENTA_DETALLES AA JOIN KIOSCO.CUENTAS BB ON AA.ID_CUENTA = BB.ID_CUENTA
JOIN KIOSCO.USUARIOS CC ON AA.ID_USUARIO = CC.ID_USUARIO
JOIN KIOSCO.PRODUCTOS DD ON AA.ID_PRODUCTO = DD.ID_PRODUCTO
ORDER BY AA.ID_CUENTA_DETALLE ASC;

/*CONSULTA PARA TODAS LOS DETALLES DE LAS CUENTAS ACTIVAS*/
SELECT CC.NOMBRE_APELLIDO_USUARIO "Cliente con Deuda"
,CONCAT(IF(CC.TIPO_DOCUMENTO_IDENTIDAD = '1','V-','E-'),IF(LENGTH(CC.DOCUMENTO_IDENTIDAD) = '9',SUBSTRING(CC.DOCUMENTO_IDENTIDAD FROM -9 FOR 3),IF(LENGTH(CC.DOCUMENTO_IDENTIDAD) = '8',SUBSTRING(CC.DOCUMENTO_IDENTIDAD FROM -8 FOR 2),SUBSTRING(CC.DOCUMENTO_IDENTIDAD FROM -7 FOR 1))),'.',SUBSTRING(CC.DOCUMENTO_IDENTIDAD FROM -6 FOR 3),'.',SUBSTRING(CC.DOCUMENTO_IDENTIDAD FROM -3)) "Cédula de Identidad"
,DD.NOMBRE_PRODUCTO "Artículo"
,IF(AA.TIPO_DETALLE = '1','Aumento de la deuda','Abono a la deuda') "Tipo de Detalle"
,AA.DESCRIPCION "Descripción del ítem"
,CONCAT('Bs. ',FORMAT(AA.MONTO_DETALLE,2)) "Monto del Producto"
,DATE_FORMAT(AA.FECHA_CREACION,'%d-%m-%y') "Fecha de Creación"
FROM KIOSCO.CUENTA_DETALLES AA JOIN KIOSCO.CUENTAS BB ON AA.ID_CUENTA = BB.ID_CUENTA
JOIN KIOSCO.USUARIOS CC ON AA.ID_USUARIO = CC.ID_USUARIO
JOIN KIOSCO.PRODUCTOS DD ON AA.ID_PRODUCTO = DD.ID_PRODUCTO
where AA.FECHA_CIERRE IS NULL
ORDER BY AA.ID_CUENTA_DETALLE ASC;

/*CONSULTA PARA TODAS LOS DETALLES DE LAS CUENTAS INACTIVAS*/
SELECT CC.NOMBRE_APELLIDO_USUARIO "Cliente con Deuda"
,CONCAT(IF(CC.TIPO_DOCUMENTO_IDENTIDAD = '1','V-','E-'),IF(LENGTH(CC.DOCUMENTO_IDENTIDAD) = '9',SUBSTRING(CC.DOCUMENTO_IDENTIDAD FROM -9 FOR 3),IF(LENGTH(CC.DOCUMENTO_IDENTIDAD) = '8',SUBSTRING(CC.DOCUMENTO_IDENTIDAD FROM -8 FOR 2),SUBSTRING(CC.DOCUMENTO_IDENTIDAD FROM -7 FOR 1))),'.',SUBSTRING(CC.DOCUMENTO_IDENTIDAD FROM -6 FOR 3),'.',SUBSTRING(CC.DOCUMENTO_IDENTIDAD FROM -3)) "Cédula de Identidad"
,DD.NOMBRE_PRODUCTO "Artículo"
,IF(AA.TIPO_DETALLE = '1','Aumento de la deuda','Abono a la deuda') "Tipo de Detalle"
,AA.DESCRIPCION "Descripción del ítem"
,CONCAT('Bs. ',FORMAT(AA.MONTO_DETALLE,2)) "Monto del Producto"
,DATE_FORMAT(AA.FECHA_CREACION,'%d-%m-%y') "Fecha de Creación"
FROM KIOSCO.CUENTA_DETALLES AA JOIN KIOSCO.CUENTAS BB ON AA.ID_CUENTA = BB.ID_CUENTA
JOIN KIOSCO.USUARIOS CC ON AA.ID_USUARIO = CC.ID_USUARIO
JOIN KIOSCO.PRODUCTOS DD ON AA.ID_PRODUCTO = DD.ID_PRODUCTO
WHERE AA.FECHA_CIERRE IS NOT NULL
ORDER BY AA.ID_CUENTA_DETALLE ASC;

/*CONSULTA PARA TODAS LOS DETALLES DE LAS CUENTAS DE UN USUARIO ESPECÍFICO*/
SELECT CC.NOMBRE_APELLIDO_USUARIO "Cliente con Deuda"
,CONCAT(IF(CC.TIPO_DOCUMENTO_IDENTIDAD = '1','V-','E-'),IF(LENGTH(CC.DOCUMENTO_IDENTIDAD) = '9',SUBSTRING(CC.DOCUMENTO_IDENTIDAD FROM -9 FOR 3),IF(LENGTH(CC.DOCUMENTO_IDENTIDAD) = '8',SUBSTRING(CC.DOCUMENTO_IDENTIDAD FROM -8 FOR 2),SUBSTRING(CC.DOCUMENTO_IDENTIDAD FROM -7 FOR 1))),'.',SUBSTRING(CC.DOCUMENTO_IDENTIDAD FROM -6 FOR 3),'.',SUBSTRING(CC.DOCUMENTO_IDENTIDAD FROM -3)) "Cédula de Identidad"
,DD.NOMBRE_PRODUCTO "Artículo"
,IF(AA.TIPO_DETALLE = '1','Aumento de la deuda','Abono a la deuda') "Tipo de Detalle"
,AA.DESCRIPCION "Descripción del ítem"
,CONCAT('Bs. ',FORMAT(AA.MONTO_DETALLE,2)) "Monto del Producto"
,DATE_FORMAT(AA.FECHA_CREACION,'%d-%m-%y') "Fecha de Creación"
FROM KIOSCO.CUENTA_DETALLES AA JOIN KIOSCO.CUENTAS BB ON AA.ID_CUENTA = BB.ID_CUENTA
JOIN KIOSCO.USUARIOS CC ON AA.ID_USUARIO = CC.ID_USUARIO
JOIN KIOSCO.PRODUCTOS DD ON AA.ID_PRODUCTO = DD.ID_PRODUCTO
WHERE CC.NOMBRE_APELLIDO_USUARIO LIKE '%%'
OR CC.DOCUMENTO_IDENTIDAD = ''
ORDER BY AA.ID_CUENTA_DETALLE ASC;