/*CONSULTA PARA TODOS LOS USUARIOS*/
SELECT CONCAT(IF(AA.TIPO_DOCUMENTO_IDENTIDAD = '1','V-','E-'),IF(LENGTH(AA.DOCUMENTO_IDENTIDAD) = '9',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -9 FOR 3),IF(LENGTH(AA.DOCUMENTO_IDENTIDAD) = '8',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -8 FOR 2),SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -7 FOR 1))),'.',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -6 FOR 3),'.',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -3)) "Cédula de Identidad"
,AA.NOMBRE_APELLIDO_USUARIO "Nombre y Apellido"
,AA.CORREO_ELECTRONICO "Email"
,CONCAT(SUBSTRING(AA.NUMERO_CONTACTO,1,4),'-',SUBSTRING(AA.NUMERO_CONTACTO,5,11)) "Número Telefónico"
,IF(AA.SEXO = '1','Masculino','Femenino') "Sexo"
,BB.NOMBRE_ESTADO "Estado"
,CC.NOMBRE_ROL "Rol"
,DATE_FORMAT(AA.FECHA_CREACION,'%d-%m-%y') "Fecha de Creación"
,IF(AA.ULTIMA_SESION IS NULL,'No ha iniciado sesión',DATE_FORMAT(AA.ULTIMA_SESION,'%d-%m-%Y')) "Último Inicio de Sesión"
FROM KIOSCO.USUARIOS AA JOIN KIOSCO.ESTADOS BB ON AA.ID_ESTADO = BB.ID_ESTADO
JOIN KIOSCO.ROLES CC ON AA.ID_ROL = CC.ID_ROL
ORDER BY AA.NOMBRE_APELLIDO_USUARIO ASC;

/*CONSULTA PARA TODOS LOS USUARIOS ACTIVOS*/
SELECT CONCAT(IF(AA.TIPO_DOCUMENTO_IDENTIDAD = '1','V-','E-'),IF(LENGTH(AA.DOCUMENTO_IDENTIDAD) = '9',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -9 FOR 3),IF(LENGTH(AA.DOCUMENTO_IDENTIDAD) = '8',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -8 FOR 2),SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -7 FOR 1))),'.',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -6 FOR 3),'.',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -3)) "Cédula de Identidad"
,AA.NOMBRE_APELLIDO_USUARIO "Nombre y Apellido"
,AA.CORREO_ELECTRONICO "Email"
,CONCAT(SUBSTRING(AA.NUMERO_CONTACTO,1,4),'-',SUBSTRING(AA.NUMERO_CONTACTO,5,11)) "Número Telefónico"
,IF(AA.SEXO = '1','Masculino','Femenino') "Sexo"
,BB.NOMBRE_ESTADO "Estado"
,CC.NOMBRE_ROL "Rol"
,DATE_FORMAT(AA.FECHA_CREACION,'%d-%m-%y') "Fecha de Creación"
,IF(AA.ULTIMA_SESION IS NULL,'No ha iniciado sesión',DATE_FORMAT(AA.ULTIMA_SESION,'%d-%m-%Y')) "Último Inicio de Sesión"
FROM KIOSCO.USUARIOS AA JOIN KIOSCO.ESTADOS BB ON AA.ID_ESTADO = BB.ID_ESTADO
JOIN KIOSCO.ROLES CC ON AA.ID_ROL = CC.ID_ROL
WHERE AA.FECHA_ELIMINACION IS NULL
ORDER BY AA.NOMBRE_APELLIDO_USUARIO ASC;

/*CONSULTA PARA TODOS LOS USUARIOS INACTIVOS*/
SELECT CONCAT(IF(AA.TIPO_DOCUMENTO_IDENTIDAD = '1','V-','E-'),IF(LENGTH(AA.DOCUMENTO_IDENTIDAD) = '9',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -9 FOR 3),IF(LENGTH(AA.DOCUMENTO_IDENTIDAD) = '8',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -8 FOR 2),SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -7 FOR 1))),'.',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -6 FOR 3),'.',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -3)) "Cédula de Identidad"
,AA.NOMBRE_APELLIDO_USUARIO "Nombre y Apellido"
,AA.CORREO_ELECTRONICO "Email"
,CONCAT(SUBSTRING(AA.NUMERO_CONTACTO,1,4),'-',SUBSTRING(AA.NUMERO_CONTACTO,5,11)) "Número Telefónico"
,IF(AA.SEXO = '1','Masculino','Femenino') "Sexo"
,BB.NOMBRE_ESTADO "Estado"
,CC.NOMBRE_ROL "Rol"
,DATE_FORMAT(AA.FECHA_CREACION,'%d-%m-%y') "Fecha de Creación"
,IF(AA.ULTIMA_SESION IS NULL,'No ha iniciado sesión',DATE_FORMAT(AA.ULTIMA_SESION,'%d-%m-%Y')) "Último Inicio de Sesión"
FROM KIOSCO.USUARIOS AA JOIN KIOSCO.ESTADOS BB ON AA.ID_ESTADO = BB.ID_ESTADO
JOIN KIOSCO.ROLES CC ON AA.ID_ROL = CC.ID_ROL
WHERE AA.FECHA_ELIMINACION IS NOT NULL
ORDER BY AA.NOMBRE_APELLIDO_USUARIO ASC;

/*CONSULTA PARA UN USUARIO ESPECÍFICO*/
SELECT CONCAT(IF(AA.TIPO_DOCUMENTO_IDENTIDAD = '1','V-','E-'),IF(LENGTH(AA.DOCUMENTO_IDENTIDAD) = '9',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -9 FOR 3),IF(LENGTH(AA.DOCUMENTO_IDENTIDAD) = '8',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -8 FOR 2),SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -7 FOR 1))),'.',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -6 FOR 3),'.',SUBSTRING(AA.DOCUMENTO_IDENTIDAD FROM -3)) "Cédula de Identidad"
,AA.NOMBRE_APELLIDO_USUARIO "Nombre y Apellido"
,AA.CORREO_ELECTRONICO "Email"
,CONCAT(SUBSTRING(AA.NUMERO_CONTACTO,1,4),'-',SUBSTRING(AA.NUMERO_CONTACTO,5,11)) "Número Telefónico"
,IF(AA.SEXO = '1','Masculino','Femenino') "Sexo"
,BB.NOMBRE_ESTADO "Estado"
,CC.NOMBRE_ROL "Rol"
,DATE_FORMAT(AA.FECHA_CREACION,'%d-%m-%y') "Fecha de Creación"
,IF(AA.ULTIMA_SESION IS NULL,'No ha iniciado sesión',DATE_FORMAT(AA.ULTIMA_SESION,'%d-%m-%Y')) "Último Inicio de Sesión"
FROM KIOSCO.USUARIOS AA JOIN KIOSCO.ESTADOS BB ON AA.ID_ESTADO = BB.ID_ESTADO
JOIN KIOSCO.ROLES CC ON AA.ID_ROL = CC.ID_ROL
WHERE AA.DOCUMENTO_IDENTIDAD = ''
OR AA.CORREO_ELECTRONICO LIKE '%%'
OR AA.NOMBRE_APELLIDO_USUARIO LIKE '%%'
OR AA.NUMERO_CONTACTO = ''
ORDER BY AA.NOMBRE_APELLIDO_USUARIO ASC;

/*CONSULTA PARA TODOS LOS PROVEEDORES CON TIPO DE SERVICIO ASOCIADO*/
SELECT AA.RIF "RIF"
,AA.NOMBRE_PROVEEDOR "Proveedor"
,IF(BB.NOMBRE_SERVICIO IS NULL,'NO TIENE TIPO DE SERVICIO ASOCIADO',BB.NOMBRE_SERVICIO) "Tipo de Servicio"
,IF(EE.PERSONA_CONTACTO IS NULL,'NO TIENE CONTACTO ASOCIADO',EE.PERSONA_CONTACTO) "Supervisor"
,IF(EE.CORREO_ELECTRONICO_1 IS NULL,'NO TIENE CORREO DE CONTACTO ASOCIADO',EE.CORREO_ELECTRONICO_1) "Correo Contacto"
,IF(EE.NUMERO_PROVEEDOR_1 IS NULL,'NO TIENE TELÉFONO DE CONTACTO ASOCIADO',EE.NUMERO_PROVEEDOR_1) "Teléfono Contacto"
,DD.NOMBRE_ESTADO "Estado"
,DATE_FORMAT(AA.FECHA_CREACION,'%d-%m-%y') "Fecha de Creación"
FROM KIOSCO.PROVEEDORES AA LEFT JOIN KIOSCO.TIPO_SERVICIOS BB ON AA.ID_TIPO_SERVICIO = BB.ID_TIPO_SERVICIO
JOIN KIOSCO.PROVEEDORES_TIPO_SERVICIOS CC ON (AA.ID_PROVEEDOR = CC.PROVEEDORES_ID_PROVEEDOR AND AA.ID_TIPO_SERVICIO = CC.TIPO_SERVICIOS_ID_TIPO_SERVICIO)
JOIN KIOSCO.ESTADOS DD ON AA.ID_ESTADO = DD.ID_ESTADO
LEFT JOIN KIOSCO.CONTACTO_PROVEEDOR EE ON AA.ID_PROVEEDOR = EE.ID_PROVEEDOR
ORDER BY AA.NOMBRE_PROVEEDOR ASC;

/*CONSULTA PARA TODOS LOS PROVEEDORES ACTIVOS CON TIPO DE SERVICIO ASOCIADO*/
SELECT AA.RIF "RIF"
,AA.NOMBRE_PROVEEDOR "Proveedor"
,IF(BB.NOMBRE_SERVICIO IS NULL,'NO TIENE TIPO DE SERVICIO ASOCIADO',BB.NOMBRE_SERVICIO) "Tipo de Servicio"
,IF(EE.PERSONA_CONTACTO IS NULL,'NO TIENE CONTACTO ASOCIADO',EE.PERSONA_CONTACTO) "Supervisor"
,IF(EE.CORREO_ELECTRONICO_1 IS NULL,'NO TIENE CORREO DE CONTACTO ASOCIADO',EE.CORREO_ELECTRONICO_1) "Correo Contacto"
,IF(EE.NUMERO_PROVEEDOR_1 IS NULL,'NO TIENE TELÉFONO DE CONTACTO ASOCIADO',EE.NUMERO_PROVEEDOR_1) "Teléfono Contacto"
,DD.NOMBRE_ESTADO "Estado"
,DATE_FORMAT(AA.FECHA_CREACION,'%d-%m-%y') "Fecha de Creación"
FROM KIOSCO.PROVEEDORES AA LEFT JOIN KIOSCO.TIPO_SERVICIOS BB ON AA.ID_TIPO_SERVICIO = BB.ID_TIPO_SERVICIO
JOIN KIOSCO.PROVEEDORES_TIPO_SERVICIOS CC ON (AA.ID_PROVEEDOR = CC.PROVEEDORES_ID_PROVEEDOR AND AA.ID_TIPO_SERVICIO = CC.TIPO_SERVICIOS_ID_TIPO_SERVICIO)
JOIN KIOSCO.ESTADOS DD ON AA.ID_ESTADO = DD.ID_ESTADO
LEFT JOIN KIOSCO.CONTACTO_PROVEEDOR EE ON AA.ID_PROVEEDOR = EE.ID_PROVEEDOR
WHERE AA.FECHA_ELIMINACION IS NULL
ORDER BY AA.NOMBRE_PROVEEDOR ASC;

/*CONSULTA PARA TODOS LOS PROVEEDORES INACTIVOS CON TIPO DE SERVICIO ASOCIADO*/
SELECT AA.RIF "RIF"
,AA.NOMBRE_PROVEEDOR "Proveedor"
,IF(BB.NOMBRE_SERVICIO IS NULL,'NO TIENE TIPO DE SERVICIO ASOCIADO',BB.NOMBRE_SERVICIO) "Tipo de Servicio"
,IF(EE.PERSONA_CONTACTO IS NULL,'NO TIENE CONTACTO ASOCIADO',EE.PERSONA_CONTACTO) "Supervisor"
,IF(EE.CORREO_ELECTRONICO_1 IS NULL,'NO TIENE CORREO DE CONTACTO ASOCIADO',EE.CORREO_ELECTRONICO_1) "Correo Contacto"
,IF(EE.NUMERO_PROVEEDOR_1 IS NULL,'NO TIENE TELÉFONO DE CONTACTO ASOCIADO',EE.NUMERO_PROVEEDOR_1) "Teléfono Contacto"
,DD.NOMBRE_ESTADO "Estado"
,DATE_FORMAT(AA.FECHA_CREACION,'%d-%m-%y') "Fecha de Creación"
FROM KIOSCO.PROVEEDORES AA LEFT JOIN KIOSCO.TIPO_SERVICIOS BB ON AA.ID_TIPO_SERVICIO = BB.ID_TIPO_SERVICIO
JOIN KIOSCO.PROVEEDORES_TIPO_SERVICIOS CC ON (AA.ID_PROVEEDOR = CC.PROVEEDORES_ID_PROVEEDOR AND AA.ID_TIPO_SERVICIO = CC.TIPO_SERVICIOS_ID_TIPO_SERVICIO)
JOIN KIOSCO.ESTADOS DD ON AA.ID_ESTADO = DD.ID_ESTADO
LEFT JOIN KIOSCO.CONTACTO_PROVEEDOR EE ON AA.ID_PROVEEDOR = EE.ID_PROVEEDOR
WHERE AA.FECHA_ELIMINACION IS NOT NULL
ORDER BY AA.NOMBRE_PROVEEDOR ASC;

/*CONSULTA PARA UN PROVEEDOR ESPECÍFICO CON TIPO DE SERVICIO ASOCIADO*/
SELECT AA.RIF "RIF"
,AA.NOMBRE_PROVEEDOR "Proveedor"
,IF(BB.NOMBRE_SERVICIO IS NULL,'NO TIENE TIPO DE SERVICIO ASOCIADO',BB.NOMBRE_SERVICIO) "Tipo de Servicio"
,IF(EE.PERSONA_CONTACTO IS NULL,'NO TIENE CONTACTO ASOCIADO',EE.PERSONA_CONTACTO) "Supervisor"
,IF(EE.CORREO_ELECTRONICO_1 IS NULL,'NO TIENE CORREO DE CONTACTO ASOCIADO',EE.CORREO_ELECTRONICO_1) "Correo Contacto"
,IF(EE.NUMERO_PROVEEDOR_1 IS NULL,'NO TIENE TELÉFONO DE CONTACTO ASOCIADO',EE.NUMERO_PROVEEDOR_1) "Teléfono Contacto"
,DD.NOMBRE_ESTADO "Estado"
,DATE_FORMAT(AA.FECHA_CREACION,'%d-%m-%y') "Fecha de Creación"
FROM KIOSCO.PROVEEDORES AA LEFT JOIN KIOSCO.TIPO_SERVICIOS BB ON AA.ID_TIPO_SERVICIO = BB.ID_TIPO_SERVICIO
JOIN KIOSCO.PROVEEDORES_TIPO_SERVICIOS CC ON (AA.ID_PROVEEDOR = CC.PROVEEDORES_ID_PROVEEDOR AND AA.ID_TIPO_SERVICIO = CC.TIPO_SERVICIOS_ID_TIPO_SERVICIO)
JOIN KIOSCO.ESTADOS DD ON AA.ID_ESTADO = DD.ID_ESTADO
LEFT JOIN KIOSCO.CONTACTO_PROVEEDOR EE ON AA.ID_PROVEEDOR = EE.ID_PROVEEDOR
WHERE AA.NOMBRE_PROVEEDOR LIKE '%%'
OR AA.RIF = ''
OR BB.NOMBRE_SERVICIO LIKE '%%'
OR EE.PERSONA_CONTACTO LIKE '%%'
ORDER BY AA.NOMBRE_PROVEEDOR ASC;