/*TABLA: ESTADOS*/
INSERT INTO KIOSCO.ESTADOS VALUES (DEFAULT,'Activo','Estado para todos los elementos que tiene todas las opciones disponibles en el sistema y puede ser utilizado por todas las entidades que tengan asignado un estado.',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.ESTADOS VALUES (DEFAULT,'Bloqueado','Estado para todos los elementos que NO tienen permitido ingresar al sistema, han sido descartados para su uso por alguna falta o discrepancia en los datos. Estos elementos no pueden ser usados por ninguna entidad del sistema.',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.ESTADOS VALUES (DEFAULT,'Inactivo','Estado para todos los elementos que han sido deshabilitados del sistema, las condiciones varían dependiendo de la entidad que tenga el estado. Mientras se encuentren en este estado no pueden ser usados en el sistema, pero debe ser validado e informado a los usuarios.',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.ESTADOS VALUES (DEFAULT,'Eliminado','Estado para todos los elementos que han sido borrados lógicamente del sistema. Estos elementos no deben ser visualizado o utilizados en ninguna parte del sistema.',CURRENT_DATE(),NULL,NULL);

DELETE FROM KIOSCO.ESTADOS WHERE ID_ESTADO = 'Activo';
DELETE FROM KIOSCO.ESTADOS WHERE ID_ESTADO = 'Bloqueado';
DELETE FROM KIOSCO.ESTADOS WHERE ID_ESTADO = 'Inactivo';
DELETE FROM KIOSCO.ESTADOS WHERE ID_ESTADO = 'Eliminado';

/*TABLA: ROLES*/
INSERT INTO KIOSCO.ROLES VALUES (DEFAULT,'Administrador','Super usuario del sistema, no tiene límites para crear, actualizar, consultar y eliminar lógicamente información. Es el único con privilegios para mover de estados a los usuarios y vendedores. (Incluye funciones de los roles Cliente, Vendedor y Empleado).','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.ROLES VALUES (DEFAULT,'Cliente','Usuario que solo debe tener cuentas por pagar o montos a su favor. Acceso solo a su información. (No incluye funciones de otros roles).','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.ROLES VALUES (DEFAULT,'Vendedor','Usuario vendedor independiente o de una empresa. Acceso solo a su información personal y los datos de los productos que vende. (Incluye funciones del rol Cliente).','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.ROLES VALUES (DEFAULT,'Empleado','Usuario que tiene acceso para consultar y agregar datos en las cuentas de los clientes, pero no puede eliminar y/o actualizar las cuentas. (Incluye funciones de los roles Cliente y Vendedor).','1',CURRENT_DATE(),NULL,NULL);

DELETE FROM KIOSCO.ROLES WHERE ID_ROL = '1';
DELETE FROM KIOSCO.ROLES WHERE ID_ROL = '2';
DELETE FROM KIOSCO.ROLES WHERE ID_ROL = '3';
DELETE FROM KIOSCO.ROLES WHERE ID_ROL = '4';
DELETE FROM KIOSCO.ROLES WHERE ID_ROL = '';

/*TABLA: USUARIOS*/
INSERT INTO KIOSCO.USUARIOS VALUES (DEFAULT,'17641081','1','Junior Casique','juniorcp86@gmail.com','04241996265','1','1','1',NULL,CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.USUARIOS VALUES (DEFAULT,'5028631','1','Jesus Casique','jesuscasique55@gmail.com','04129935638','1','1','1',NULL,CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.USUARIOS VALUES (DEFAULT,'','','','','','','',,'',NULL,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.USUARIOS VALUES (DEFAULT,'','','','','','','',,'',NULL,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO KIOSCO.USUARIOS VALUES (DEFAULT,'','','','','','','',,'',NULL,CURRENT_TIMESTAMP,NULL,NULL);

DELETE FROM KIOSCO.USUARIOS WHERE DOCUMENTO_IDENTIDAD = '17641081';
DELETE FROM KIOSCO.USUARIOS WHERE DOCUMENTO_IDENTIDAD = '5028631';
DELETE FROM KIOSCO.USUARIOS WHERE DOCUMENTO_IDENTIDAD = '';

/*TABLA: TIPO_SERVICIOS*/
INSERT INTO KIOSCO.TIPO_SERVICIOS VALUES (DEFAULT,'Tarjetas telefónicas Movistar','Distribución de tarjetas telefónicas para Movistar.',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.TIPO_SERVICIOS VALUES (DEFAULT,'Tarjetas telefónicas Movilnet','Distribución de tarjetas telefónicas para Movilnet.',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.TIPO_SERVICIOS VALUES (DEFAULT,'Tarjetas telefónicas Digitel','Distribución de tarjetas telefónicas para Digitel.',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.TIPO_SERVICIOS VALUES (DEFAULT,'Tarjetas telefónicas Direct TV','Distribución de tarjetas telefónicas para Direct TV.',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.TIPO_SERVICIOS VALUES (DEFAULT,'Tarjetas telefónicas llamadas internacionales','Distribución de tarjetas telefónicas para llamadas internacionales.',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.TIPO_SERVICIOS VALUES (DEFAULT,'Revistas nacionales','Distribución de revistas nacionales.',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.TIPO_SERVICIOS VALUES (DEFAULT,'Revistas importadas','Distribución de revistas importadas.',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.TIPO_SERVICIOS VALUES (DEFAULT,'Chucherías nacionales','Distribución de chucherías nacionales.',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.TIPO_SERVICIOS VALUES (DEFAULT,'Chucherías importadas','Distribución de chucherías importadas.',CURRENT_DATE(),NULL,NULL);

DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE ID_TIPO_SERVICIO = '1';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE ID_TIPO_SERVICIO = '2';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE ID_TIPO_SERVICIO = '3';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE ID_TIPO_SERVICIO = '4';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE ID_TIPO_SERVICIO = '5';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE ID_TIPO_SERVICIO = '6';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE ID_TIPO_SERVICIO = '7';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE ID_TIPO_SERVICIO = '8';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE ID_TIPO_SERVICIO = '9';
DELETE FROM KIOSCO.TIPO_SERVICIOS WHERE ID_TIPO_SERVICIO = '';

/*TABLA: PROVEEDORES*/
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-294556507','Distribuida Careste, C.A.','1','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-000067481','C.A. Cigarrera Bigott','1','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-313691976','Comunicaciones Movilcard 21, C.A.','1','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-304689713','Corporación Digitel','1','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'J-305807574','Distribuidora Sobralia C.A.','1','1',CURRENT_DATE(),NULL,NULL);
INSERT INTO KIOSCO.PROVEEDORES VALUES (DEFAULT,'','','','',CURRENT_DATE(),NULL,NULL);

DELETE FROM KIOSCO.PROVEEDORES WHERE RIF = 'J-294556507';
DELETE FROM KIOSCO.PROVEEDORES WHERE RIF = 'J-000067481';
DELETE FROM KIOSCO.PROVEEDORES WHERE RIF = 'J-313691976';
DELETE FROM KIOSCO.PROVEEDORES WHERE RIF = 'J-304689713';
DELETE FROM KIOSCO.PROVEEDORES WHERE RIF = 'J-305807574';
DELETE FROM KIOSCO.PROVEEDORES WHERE RIF = '';

/*TABLA: CONTACTO_PROVEEDOR*/
INSERT INTO KIOSCO.CONTACTO_PROVEEDOR VALUES (DEFAULT,'1','Doni','04241234567',NULL,NULL,'donilatin@hotmail.com',NULL,NULL);
INSERT INTO KIOSCO.CONTACTO_PROVEEDOR VALUES (DEFAULT,'','','',NULL,NULL,'',NULL,NULL);

DELETE FROM KIOSCO.CONTACTO_PROVEEDOR WHERE ID_CONTACTO = '1';
DELETE FROM KIOSCO.CONTACTO_PROVEEDOR WHERE ID_CONTACTO = '';

/*TABLA: PROVEEDORES_TIPO_SERVICIOS*/
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('1','1');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('3','1');
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('','');

DELETE FROM KIOSCO.PROVEEDORES_TIPO_SERVICIOS WHERE PROVEEDORES_ID_PROVEEDOR = '1' AND TIPO_SERVICIOS_ID_TIPO_SERVICIO = '1';
DELETE FROM KIOSCO.PROVEEDORES_TIPO_SERVICIOS WHERE PROVEEDORES_ID_PROVEEDOR = '3' AND TIPO_SERVICIOS_ID_TIPO_SERVICIO = '1';
DELETE FROM KIOSCO.PROVEEDORES_TIPO_SERVICIOS WHERE PROVEEDORES_ID_PROVEEDOR = '' AND TIPO_SERVICIOS_ID_TIPO_SERVICIO = '';

/*TABLA: PRODUCTOS*/
INSERT INTO KIOSCO.PRODUCTOS VALUES (DEFAULT,'Chocolate de leche pequeño','Chocolate de leche pequeño 100 Gramos.','1',CURRENT_DATE,NULL,NULL);
INSERT INTO KIOSCO.PRODUCTOS VALUES (DEFAULT,'','','1',CURRENT_DATE,NULL,NULL);

DELETE FROM KIOSCO.PRODUCTOS WHERE ID_PRODUCTO = '1';
DELETE FROM KIOSCO.PRODUCTOS WHERE ID_PRODUCTO = '';

/*TABLA: PROVEEDORES_PRODUCTOS*/
INSERT INTO KIOSCO.PROVEEDORES_TIPO_SERVICIOS VALUES ('1','1');
DELETE FROM KIOSCO.PROVEEDORES_TIPO_SERVICIOS WHERE PROVEEDORES_ID_PROVEEDOR = '' AND TIPO_SERVICIOS_ID_TIPO_SERVICIO = '';

/*TABLA: IVA*/


/*TABLA: COSTO_PRODUCTOS*/


/*TABLA: CUENTAS*/
INSERT INTO KIOSCO.CUENTAS VALUES (DEFAULT,'','',CURRENT_DATE,NULL,NULL);

DELETE FROM KIOSCO.CUENTAS WHERE ID_CUENTA = '' AND ID_USUARIO = '';

/*TABLA: CUENTAS_DETALLES*/
INSERT INTO KIOSCO.CUENTAS VALUES (DEFAULT,'','',CURRENT_DATE,NULL,NULL);

DELETE FROM KIOSCO.CUENTAS WHERE ID_CUENTA = '' AND ID_USUARIO = '';



